<a href="https://colab.research.google.com/github/sitoan/sentence-transformer/blob/main/20231020_sentence_transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#SENTENCE TRANSFORMERS

##INSTALL PACKAGE

In [ ]:
!pip install sentence_transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 2.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.7/7.7 MB 46.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 71.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.0/302.0 kB 31.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 97.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 68.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.0/295.0 kB 35.9 MB/s eta 0:00:00
  Created wheel for sentence_transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125923 sha256=13d1d3f9fdc9713e2e6f912865e318e532de804a8567d3d69561f7dc0dc739ca
  Stored in directory: /root/.cache/pip/wheels/62/f2/10/1e606fd5f02395388f74e7462910fe851042f97238cbbd902f
Successfully built sentence_transformers


##USING SENTENCE TRANSFORMERS



In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
from sentence_transformers import SentenceTransformer

#Load the model
model = SentenceTransformer('all-MiniLM-L6-v2')

#Our sentences we like to encode
sentences = ['This framework generates embeddings for each input sentence',
    'Sentences are passed as a list of string.',
    'The quick brown fox jumps over the lazy dog.']

#Sentences are encoded by calling model.encode()
embeddings = model.encode(sentences)

#Print the embeddings
for sentence, embedding in zip(sentences, embeddings):
    print("Vector length:", len(embedding))
    print("Sentence:", sentence)
    print("Embedding:", embedding)
    print("")


Vector length: 384
Sentence: This framework generates embeddings for each input sentence
Embedding: [-1.37173552e-02 -4.28515449e-02 -1.56286024e-02  1.40537303e-02
  3.95537727e-02  1.21796280e-01  2.94334106e-02 -3.17524187e-02
  3.54959629e-02 -7.93139935e-02  1.75878741e-02 -4.04369719e-02
  4.97259349e-02  2.54912246e-02 -7.18700588e-02  8.14968869e-02
  1.47069141e-03  4.79626991e-02 -4.50336412e-02 -9.92174670e-02
 -2.81769745e-02  6.45046085e-02  4.44670543e-02 -4.76217009e-02
 -3.52952331e-02  4.38671783e-02 -5.28566055e-02  4.33063833e-04
  1.01921506e-01  1.64072234e-02  3.26996595e-02 -3.45986746e-02
  1.21339476e-02  7.94870779e-02  4.58345609e-03  1.57777797e-02
 -9.68206208e-03  2.87625659e-02 -5.05805984e-02 -1.55793717e-02
 -2.87906546e-02 -9.62280575e-03  3.15556750e-02  2.27349028e-02
  8.71449187e-02 -3.85027491e-02 -8.84718448e-02 -8.75498448e-03
 -2.12343335e-02  2.08923239e-02 -9.02077407e-02 -5.25732562e-02
 -1.05638904e-02  2.88310610e-02 -1.61455162e-02  6.178

##SIMILARITY

In [ ]:
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('all-MiniLM-L6-v2')

sentences = ['A man is eating food.',
          'A man is eating a piece of bread.',
          'The girl is carrying a baby.',
          'A man is riding a horse.',
          'A woman is playing violin.',
          'Two men pushed carts through the woods.',
          'A man is riding a white horse on an enclosed ground.',
          'A monkey is playing drums.',
          'Someone in a gorilla costume is playing a set of drums.'
          ]

#Encode all sentences
embeddings = model.encode(sentences)

#Compute cosine similarity between all pairs
cos_sim = util.cos_sim(embeddings, embeddings)
print(cos_sim)

#Add all pairs to a list with their cosine similarity score
all_sentence_combinations = []
for i in range(len(cos_sim)-1):
    for j in range(i+1, len(cos_sim)):
        all_sentence_combinations.append([cos_sim[i][j], i, j])

#Sort list by the highest cosine similarity score
all_sentence_combinations = sorted(all_sentence_combinations, key=lambda x: x[0], reverse=True)

print("Top-5 most similar pairs:")
for score, i, j in all_sentence_combinations:
    print("{} \t {} \t {:.4f}".format(sentences[i], sentences[j], cos_sim[i][j]))

tensor([[ 1.0000,  0.7553, -0.1050,  0.2474, -0.0704, -0.0333,  0.1707,  0.0476,
          0.0630],
        [ 0.7553,  1.0000, -0.0610,  0.1442, -0.0809, -0.0216,  0.1157,  0.0362,
          0.0216],
        [-0.1050, -0.0610,  1.0000, -0.1088,  0.0217, -0.0413, -0.0928,  0.0231,
          0.0247],
        [ 0.2474,  0.1442, -0.1088,  1.0000, -0.0348,  0.0362,  0.7369,  0.0821,
          0.1389],
        [-0.0704, -0.0809,  0.0217, -0.0348,  1.0000, -0.1654, -0.0592,  0.1961,
          0.2564],
        [-0.0333, -0.0216, -0.0413,  0.0362, -0.1654,  1.0000,  0.0769, -0.0380,
         -0.0895],
        [ 0.1707,  0.1157, -0.0928,  0.7369, -0.0592,  0.0769,  1.0000,  0.0495,
          0.1191],
        [ 0.0476,  0.0362,  0.0231,  0.0821,  0.1961, -0.0380,  0.0495,  1.0000,
          0.6433],
        [ 0.0630,  0.0216,  0.0247,  0.1389,  0.2564, -0.0895,  0.1191,  0.6433,
          1.0000]])
Top-5 most similar pairs:
A man is eating food. 	 A man is eating a piece of bread. 	 0.7553
A man 

In [ ]:
from sentence_transformers import SentenceTransformer, util
import numpy as np

model = SentenceTransformer('all-MiniLM-L6-v2')

sentences = ['A man is eating food.',
          'A man is eating a piece of bread.',
          'The girl is carrying a baby.',
          'A man is riding a horse.',
          'A woman is playing violin.',
          'Two men pushed carts through the woods.',
          'A man is riding a white horse on an enclosed ground.',
          'A monkey is playing drums.',
          'Someone in a gorilla costume is playing a set of drums.',
          'Nam sinh ở Tp.HCM',
          'Nam có quốc tịch Việt Nam'
          ]

sentence = input("Enter a sentence:")
#Encode all sentences
embeddings = model.encode(sentences)
embedding = model.encode([sentence])

#Compute cosine similarity between all pairs
cos_sim = util.cos_sim(embedding, embeddings)

print(cos_sim)

print(np.argmax(cos_sim))

i = np.argmax(cos_sim)
print("The most similarity sentence: ", sentences[i])

Enter a sentence:
tensor([[ 0.0253, -0.0020, -0.0563,  0.0088, -0.0518, -0.0064,  0.0029,  0.0081,
          0.0520,  0.1358,  0.0722]])
tensor(9)
The most similarity sentence:  Nam sinh ở Tp.HCM


#CHATBOT

In [ ]:
'''
- Cung cấp 5 thông tin về HCMC
- Tạo chatbot hỏi đáp
'''
from sentence_transformers import SentenceTransformer, util
import numpy as np

model = SentenceTransformer('all-MiniLM-L6-v2')

sentences = [
    'Tp.HCM là thành phố lớn nhất Việt Nam',
    'Tp.HCM là thành phố đông dân nhất Việt Nam',
    'Dân số Tp.HCM trên 10 triệu người',
    'Tp.HCM trước đây là Sài Gòn',
    'Tp.HCM ở Miền Nam Việt Nam'
          ]

#Encode all sentences
embeddings = model.encode(sentences)

while True:
  sentence = input("Enter a question:")
  if sentence == '': break

  embedding = model.encode([sentence])

  #Compute cosine similarity between all pairs
  cos_sim = util.cos_sim(embedding, embeddings)

  print(cos_sim)
  print(np.argmax(cos_sim))

  i = np.argmax(cos_sim)
  print("Answer: ", sentences[i])

Enter a question:


In [ ]:
'''
- Cung cấp 5 thông tin về HCMC
- Tạo chatbot hỏi đáp
'''
from sentence_transformers import SentenceTransformer, util
import numpy as np

model = SentenceTransformer('all-MiniLM-L6-v2')

# Load chatbot knowledge
with open('/content/drive/MyDrive/AI/data/knowledge.txt', 'r') as f:
    sentences = f.readlines()


print(type(sentences))
#Encode all sentences
embeddings = model.encode(sentences)

while True:
  sentence = input("Enter a question:")
  if sentence == '': break

  embedding = model.encode([sentence])

  #Compute cosine similarity between all pairs
  cos_sim = util.cos_sim(embedding, embeddings)

  print(cos_sim)
  print(np.argmax(cos_sim))

  i = np.argmax(cos_sim)
  print("Answer: ", sentences[i])

<class 'list'>
Enter a question:


In [ ]:
'''
- Cung cấp 5 thông tin về HCMC
- Tạo chatbot hỏi đáp
'''
from sentence_transformers import SentenceTransformer, util
import numpy as np

model = SentenceTransformer('all-MiniLM-L6-v2')

sentences = [
            "Vinh ngu",
            "Vinh rat ngu"
          ]

#Encode all sentences
embeddings = model.encode(sentences)

while True:
  sentence = input("Enter a question:")
  if sentence == '': break

  embedding = model.encode([sentence])

  #Compute cosine similarity between all pairs
  cos_sim = util.cos_sim(embedding, embeddings)

  print(cos_sim)
  print(np.argmax(cos_sim))

  i = np.argmax(cos_sim)
  if cos_sim[0][i]<0.7:
    print("hong bic")
  else:
    print("Answer: ", sentences[i])

Enter a question:


##CREATE A KD_TREE


In [ ]:
!pip install dill

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 2.5 MB/s eta 0:00:00


In [ ]:
import numpy as np
import time
import dill as pickle
from scipy.spatial import KDTree


print("Building the KD-Tree...")
kdtree = KDTree(embeddings, leafsize=100)

print("Storing the KD-Tree...")
with open(f"/content/drive/MyDrive/AI/data/kdtree.bin",'wb') as outfile:
    pickle.dump(kdtree, outfile)

Building the KD-Tree...
Storing the KD-Tree...


##USING KD-TREE

In [ ]:
with open(f"/content/drive/MyDrive/AI/data/kdtree.bin", 'rb') as file:
        kdtree: KDTree = pickle.load(file)
print("The KD-Tree is loaded")

The KD-Tree is loaded


In [ ]:
while True:
  sentence = input("Enter a question:")
  if sentence == '': break

  embedding = model.encode([sentence])

  #Compute cosine similarity between all pairs
  cos_sim = util.cos_sim(embedding, embeddings)

  print(cos_sim)
  print(np.argmax(cos_sim))

  i = np.argmax(cos_sim)

  if cos_sim[0][i] < 0.7:
    print("I don't known.")
  else:
    print("Answer: ", sentences[i])

Enter a question:hllo
tensor([[0.1946, 0.1442]])
tensor(0)
I don't known.
Enter a question:
