<a href="https://colab.research.google.com/github/sitoan/sentence-transformer/blob/main/20231020_sentence_transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#SENTENCE TRANSFORMERS

##INSTALL PACKAGE

In [1]:
!pip install sentence_transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.3/163.3 kB 1.7 MB/s eta 0:00:00
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-many

##USING SENTENCE TRANSFORMERS



In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
from sentence_transformers import SentenceTransformer

#Load the model
model = SentenceTransformer('all-MiniLM-L6-v2')

#Our sentences we like to encode
sentences = ['This framework generates embeddings for each input sentence',
    'Sentences are passed as a list of string.',
    'The quick brown fox jumps over the lazy dog.']

#Sentences are encoded by calling model.encode()
embeddings = model.encode(sentences)

#Print the embeddings
for sentence, embedding in zip(sentences, embeddings):
    print("Vector length:", len(embedding))
    print("Sentence:", sentence)
    print("Embedding:", embedding)
    print("")


/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.7k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Vector length: 384
Sentence: This framework generates embeddings for each input sentence
Embedding: [-1.37173338e-02 -4.28515300e-02 -1.56286079e-02  1.40537489e-02
  3.95537764e-02  1.21796295e-01  2.94334106e-02 -3.17524225e-02
  3.54959629e-02 -7.93139786e-02  1.75878834e-02 -4.04370017e-02
  4.97259051e-02  2.54912414e-02 -7.18700439e-02  8.14969167e-02
  1.47071737e-03  4.79627103e-02 -4.50336374e-02 -9.92174968e-02
 -2.81769596e-02  6.45046607e-02  4.44670618e-02 -4.76216935e-02
 -3.52952406e-02  4.38671671e-02 -5.28565869e-02  4.33066773e-04
  1.01921484e-01  1.64072216e-02  3.26996297e-02 -3.45986709e-02
  1.21339019e-02  7.94870928e-02  4.58344584e-03  1.57778431e-02
 -9.68207046e-03  2.87625995e-02 -5.05806319e-02 -1.55793484e-02
 -2.87906323e-02 -9.62281786e-03  3.15556750e-02  2.27348618e-02
  8.71449336e-02 -3.85027491e-02 -8.84718522e-02 -8.75501335e-03
 -2.12343000e-02  2.08923332e-02 -9.02077407e-02 -5.25732227e-02
 -1.05639081e-02  2.88310777e-02 -1.61454733e-02  6.178

##SIMILARITY

In [5]:
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('all-MiniLM-L6-v2')

sentences = ['A man is eating food.',
          'A man is eating a piece of bread.',
          'The girl is carrying a baby.',
          'A man is riding a horse.',
          'A woman is playing violin.',
          'Two men pushed carts through the woods.',
          'A man is riding a white horse on an enclosed ground.',
          'A monkey is playing drums.',
          'Someone in a gorilla costume is playing a set of drums.'
          ]

#Encode all sentences
embeddings = model.encode(sentences)

#Compute cosine similarity between all pairs
cos_sim = util.cos_sim(embeddings, embeddings)
print(cos_sim)

#Add all pairs to a list with their cosine similarity score
all_sentence_combinations = []
for i in range(len(cos_sim)-1):
    for j in range(i+1, len(cos_sim)):
        all_sentence_combinations.append([cos_sim[i][j], i, j])

#Sort list by the highest cosine similarity score
all_sentence_combinations = sorted(all_sentence_combinations, key=lambda x: x[0], reverse=True)

print("Top-5 most similar pairs:")
for score, i, j in all_sentence_combinations:
    print("{} \t {} \t {:.4f}".format(sentences[i], sentences[j], cos_sim[i][j]))

tensor([[ 1.0000,  0.7553, -0.1050,  0.2474, -0.0704, -0.0333,  0.1707,  0.0476,
          0.0630],
        [ 0.7553,  1.0000, -0.0610,  0.1442, -0.0809, -0.0216,  0.1157,  0.0362,
          0.0216],
        [-0.1050, -0.0610,  1.0000, -0.1088,  0.0217, -0.0413, -0.0928,  0.0231,
          0.0247],
        [ 0.2474,  0.1442, -0.1088,  1.0000, -0.0348,  0.0362,  0.7369,  0.0821,
          0.1389],
        [-0.0704, -0.0809,  0.0217, -0.0348,  1.0000, -0.1654, -0.0592,  0.1961,
          0.2564],
        [-0.0333, -0.0216, -0.0413,  0.0362, -0.1654,  1.0000,  0.0769, -0.0380,
         -0.0895],
        [ 0.1707,  0.1157, -0.0928,  0.7369, -0.0592,  0.0769,  1.0000,  0.0495,
          0.1191],
        [ 0.0476,  0.0362,  0.0231,  0.0821,  0.1961, -0.0380,  0.0495,  1.0000,
          0.6433],
        [ 0.0630,  0.0216,  0.0247,  0.1389,  0.2564, -0.0895,  0.1191,  0.6433,
          1.0000]])
Top-5 most similar pairs:
A man is eating food. 	 A man is eating a piece of bread. 	 0.7553
A man 

In [6]:
from sentence_transformers import SentenceTransformer, util
import numpy as np

model = SentenceTransformer('all-MiniLM-L6-v2')

sentences = ['A man is eating food.',
          'A man is eating a piece of bread.',
          'The girl is carrying a baby.',
          'A man is riding a horse.',
          'A woman is playing violin.',
          'Two men pushed carts through the woods.',
          'A man is riding a white horse on an enclosed ground.',
          'A monkey is playing drums.',
          'Someone in a gorilla costume is playing a set of drums.',
          'Nam sinh ở Tp.HCM',
          'Nam có quốc tịch Việt Nam'
          ]

sentence = input("Enter a sentence:")
#Encode all sentences
embeddings = model.encode(sentences)
embedding = model.encode([sentence])

#Compute cosine similarity between all pairs
cos_sim = util.cos_sim(embedding, embeddings)

print(cos_sim)

print(np.argmax(cos_sim))

i = np.argmax(cos_sim)
print("The most similarity sentence: ", sentences[i])

Enter a sentence:he
tensor([[ 0.1090,  0.0876, -0.1705,  0.1210, -0.0940, -0.0084,  0.1128,  0.0325,
          0.0623,  0.0929,  0.0632]])
tensor(3)
The most similarity sentence:  A man is riding a horse.


#CHATBOT

In [ ]:
'''
- Cung cấp 5 thông tin về HCMC
- Tạo chatbot hỏi đáp
'''
from sentence_transformers import SentenceTransformer, util
import numpy as np

model = SentenceTransformer('all-MiniLM-L6-v2')

sentences = [
    'Tp.HCM là thành phố lớn nhất Việt Nam',
    'Tp.HCM là thành phố đông dân nhất Việt Nam',
    'Dân số Tp.HCM trên 10 triệu người',
    'Tp.HCM trước đây là Sài Gòn',
    'Tp.HCM ở Miền Nam Việt Nam'
          ]

#Encode all sentences
embeddings = model.encode(sentences)

while True:
  sentence = input("Enter a question:")
  if sentence == '': break

  embedding = model.encode([sentence])

  #Compute cosine similarity between all pairs
  cos_sim = util.cos_sim(embedding, embeddings)

  print(cos_sim)
  print(np.argmax(cos_sim))

  i = np.argmax(cos_sim)
  print("Answer: ", sentences[i])

Enter a question:


In [8]:
'''
- Cung cấp 5 thông tin về HCMC
- Tạo chatbot hỏi đáp
'''
from sentence_transformers import SentenceTransformer, util
import numpy as np

model = SentenceTransformer('all-MiniLM-L6-v2')

# Load chatbot knowledge
with open('/content/drive/MyDrive/AI/data/knowledge.txt', 'r') as f:
    sentences = f.readlines()


print(type(sentences))
#Encode all sentences
embeddings = model.encode(sentences)

while True:
  sentence = input("Enter a question:")
  if sentence == '': break

  embedding = model.encode([sentence])

  #Compute cosine similarity between all pairs
  cos_sim = util.cos_sim(embedding, embeddings)

  print(cos_sim)
  print(np.argmax(cos_sim))

  i = np.argmax(cos_sim)
  print("Answer: ", sentences[i])


<class 'list'>
Enter a question:Nam
tensor([[0.5263, 0.5289, 0.2677, 0.2738, 0.6438]])
tensor(4)
Answer:  Tp.HCM ở Miền Nam Việt Nam
Enter a question:0
tensor([[0.0576, 0.0763, 0.1455, 0.1456, 0.0719]])
tensor(3)
Answer:  Tp.HCM trước đây là Sài Gòn

Enter a question:.
tensor([[0.0887, 0.0704, 0.1226, 0.1035, 0.0810]])
tensor(2)
Answer:  Dân số Tp.HCM trên 10 triệu người

Enter a question: 
tensor([[0.0893, 0.0775, 0.1507, 0.1315, 0.0907]])
tensor(2)
Answer:  Dân số Tp.HCM trên 10 triệu người

Enter a question:


##CREATE A KD_TREE


In [9]:
!pip install dill

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 2.9 MB/s eta 0:00:00


In [10]:
import numpy as np
import time
import dill as pickle
from scipy.spatial import KDTree


print("Building the KD-Tree...")
kdtree = KDTree(embeddings, leafsize=100)

print("Storing the KD-Tree...")
with open(f"/content/drive/MyDrive/AI/data/kdtree.bin",'wb') as outfile:
    pickle.dump(kdtree, outfile)

Building the KD-Tree...
Storing the KD-Tree...


##USING KD-TREE

In [11]:
with open(f"/content/drive/MyDrive/AI/data/kdtree.bin", 'rb') as file:
        kdtree: KDTree = pickle.load(file)
print("The KD-Tree is loaded")

The KD-Tree is loaded


In [12]:
while True:
  sentence = input("Enter a question:")
  if sentence == '': break

  embedding = model.encode([sentence])

  #Compute cosine similarity between all pairs
  cos_sim = util.cos_sim(embedding, embeddings)

  print(cos_sim)
  print(np.argmax(cos_sim))

  i = np.argmax(cos_sim)

  if cos_sim[0][i] < 0.7:
    print("I don't known.")
  else:
    print("Answer: ", sentences[i])

Enter a question:hii
tensor([[0.2617, 0.2629, 0.3174, 0.2262, 0.2395]])
tensor(2)
I don't known.
Enter a question: 
tensor([[0.0893, 0.0775, 0.1507, 0.1315, 0.0907]])
tensor(2)
I don't known.
Enter a question:
